#!/bin/bash
function check_create_dir {
  if [ ! -d "./$1" ]; then
    mkdir "./$1"
  fi
}

# Create build environment
check_create_dir BUILD
check_create_dir BUILDROOT
check_create_dir RPMS
check_create_dir SOURCES
check_create_dir SPECS
check_create_dir SRPMS

if [ ! -f './SOURCES/poppler-0.12.4.tar.gz' ]; then
  wget 'http://poppler.freedesktop.org/poppler-0.12.4.tar.gz' -O './SOURCES/poppler-0.12.4.tar.gz'
fi

rpmbuild --define "_topdir `pwd`" -ba 'SPECS/poppler.spec'
echo Your packages are available at $PWD/RPMS

